apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
# ArgoCD official installation - v3.0.12 (latest stable)
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.12/manifests/install.yaml
# Namespace
- namespace.yaml
# ArgoCD Ingress (additional resource, not a patch)
- argocd-ingress.yaml

patches:
# Patch service to use LoadBalancer type
- patch: |-
    - op: replace
      path: /spec/type
      value: LoadBalancer
  target:
    kind: Service
    name: argocd-server
    namespace: argocd
# Apply ConfigMap customizations (Pulumi Stack support, RBAC, etc.)
- path: argocd-cm-patch.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
    namespace: argocd

images:
# Use the same version for all ArgoCD components
- name: quay.io/argoproj/argocd
  newTag: v3.0.12
- name: redis
  newTag: 7.0.15-alpine
