apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
# ArgoCD official installation
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patchesStrategicMerge:
- argocd-server-service.yaml
- argocd-cm.yaml

patches:
# Enable insecure mode for easier local development (disable in production)
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: --insecure
  target:
    kind: Deployment
    name: argocd-server
