apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: myapp-infrastructure
  namespace: pulumi-system
  labels:
    app.kubernetes.io/name: myapp-infrastructure
    app.kubernetes.io/part-of: myapp
    app.kubernetes.io/managed-by: ArgoCD
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  # Stack configuration
  stack: dev
  projectRepo: https://github.com/kjenney/gitops-ultra # Replace with your repo
  repoDir: infrastructure/pulumi
  branch: refs/heads/main
  
  # Pulumi program configuration
  config:
    aws:region: us-west-2
    project:prefix: myapp-dev
    kubernetes:namespace: myapp-dev
    
  # Secrets for credentials
  secretsProvider:
    type: passphrase
    passphraseSecretRef:
      name: pulumi-api-secret
      key: configPassphrase
      
  # Environment variables for AWS access
  envSecrets:
  - secret: aws-credentials
    env:
      AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: AWS_DEFAULT_REGION
      
  # Resource limits for the Pulumi program execution
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
      
  # Refresh the stack on every sync
  refresh: true
  
  # Continue on errors (set to false for production)
  continueResyncOnCommitMatch: true
  
  # Retry configuration
  retryOnUpdateConflict: true
  
  # Outputs that will be available to other resources
  # These can be referenced by other applications
  outputs:
  - bucketName
  - bucketArn
  - queueUrl
  - queueArn
  - serviceAccountRoleArn
  - kubernetesNamespace
  - kubernetesServiceAccountName
