apiVersion: v1
kind: ConfigMap
metadata:
  name: pulumi-operator-config
  namespace: pulumi-system
  labels:
    app.kubernetes.io/name: pulumi-operator
    app.kubernetes.io/part-of: pulumi-operator
data:
  # Configure the operator with default settings
  PULUMI_BACKEND_URL: "file://./state"  # Use local file backend by default
  PULUMI_CONFIG_PASSPHRASE: ""  # Will be overridden by secret
  
---
apiVersion: v1
kind: Secret
metadata:
  name: pulumi-api-secret
  namespace: pulumi-system
  labels:
    app.kubernetes.io/name: pulumi-operator
    app.kubernetes.io/part-of: pulumi-operator
type: Opaque
stringData:
  # Pulumi access token (optional, for Pulumi Cloud backend)
  accessToken: ""
  # Config passphrase for state encryption
  configPassphrase: "mydefaultpassphrase"  # Change this in production
  
---
# AWS credentials for Pulumi to manage AWS resources
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: pulumi-system
  labels:
    app.kubernetes.io/name: pulumi-operator
    app.kubernetes.io/part-of: pulumi-operator
type: Opaque
stringData:
  # AWS credentials - replace with actual values or use IRSA
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "us-west-2"
