apiVersion: v1
kind: Service
metadata:
  name: myapp-dev-service
  namespace: myapp-dev
  labels:
    app.kubernetes.io/name: myapp-dev-service
    app.kubernetes.io/managed-by: ArgoCD
    app.kubernetes.io/part-of: myapp
    app.kubernetes.io/component: service
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: myapp-dev
    app.kubernetes.io/component: application

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-dev-ingress
  namespace: myapp-dev
  labels:
    app.kubernetes.io/name: myapp-dev-ingress
    app.kubernetes.io/managed-by: ArgoCD
    app.kubernetes.io/part-of: myapp
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - myapp-dev.example.com
    secretName: myapp-dev-tls
  rules:
  - host: myapp-dev.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp-dev-service
            port:
              number: 80
