---
# ArgoCD Application for deploying sample applications
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-applications
  namespace: argocd
  labels:
    app.kubernetes.io/name: sample-applications
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: myapp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  
  source:
    repoURL: https://github.com/your-org/gitops-ultra  # TODO: Update with actual repo URL
    targetRevision: HEAD
    path: examples/applications
    
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-dev
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=false  # Namespace should already exist from infrastructure
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  # Health check for applications
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas  # Allow HPA to manage replicas
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    jsonPointers:
    - /status
